=== dlabaja/MrtkiBlockReloaded/data/item.schema.json
{
  "definitions": {
    "declension": {
      "type": "object",
      "properties": {
        "matches": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "replacements": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["matches", "replacements"]
    }
  },
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "ID skupiny"
    },
    "matchUpperCase": {
      "type": "boolean",
      "description": "True pokud mají být matchovány i matche psané velkými písmeny (Babiš -> BABIŠ)"
    },
    "matchLowerCase": {
      "type": "boolean",
      "description": "True pokud mají být matchovány i matche psané malými písmeny (Babiš -> babiš)"
    },
    "cases": {
      "type": "object",
      "properties": {
        "1": {"$ref": "#/definitions/declension"},
        "2": {"$ref": "#/definitions/declension"},
        "3": {"$ref": "#/definitions/declension"},
        "4": {"$ref": "#/definitions/declension"},
        "5": {"$ref": "#/definitions/declension"},
        "6": {"$ref": "#/definitions/declension"},
        "7": {"$ref": "#/definitions/declension"}
      },
      "required": ["1", "2", "3", "4", "5", "6", "7"]
    },
    "adjectives": {
      "type": "object",
      "properties": {
        "to": {"$ref": "#/definitions/declension"},
        "ta": {"$ref": "#/definitions/declension"},
        "ten": {"$ref": "#/definitions/declension"},
        "ti": {"$ref": "#/definitions/declension"},
        "ty": {"$ref": "#/definitions/declension"},
        "te": {"$ref": "#/definitions/declension"},
        "tu": {"$ref": "#/definitions/declension"},
        "tou": {"$ref": "#/definitions/declension"},
        "tim": {"$ref": "#/definitions/declension"},
        "tech": {"$ref": "#/definitions/declension"},
        "temi": {"$ref": "#/definitions/declension"}
      },
      "required": ["to", "ta", "ten", "ti", "ty", "te", "tu", "tou", "tim", "tech", "temi"]
    }
  },
  "required": ["name", "matchUpperCase", "matchLowerCase", "cases"]
}

=== dlabaja/MrtkiBlockReloaded/data/other-sources/microslop/items/xbox.json
{
  "name": "xbox",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Xbox"
      ],
      "replacements": [
        "GreedYbox"
      ]
    },
    "2": {
      "matches": [
        "Xboxu"
      ],
      "replacements": [
        "GreedYboxu"
      ]
    },
    "3": {
      "matches": [
        "Xboxu"
      ],
      "replacements": [
        "GreedYboxu"
      ]
    },
    "4": {
      "matches": [
        "Xbox"
      ],
      "replacements": [
        "GreedYbox"
      ]
    },
    "5": {
      "matches": [
        "Xboxe"
      ],
      "replacements": [
        "GreedYboxe"
      ]
    },
    "6": {
      "matches": [
        "Xboxu"
      ],
      "replacements": [
        "GreedYboxu"
      ]
    },
    "7": {
      "matches": [
        "Xboxem"
      ],
      "replacements": [
        "GreedYboxem"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/kalousek.json
{
  "name": "kalousek",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Kalousek",
        "Miroslav Kalousek"
      ],
      "replacements": [
        "Arcikacíř Mirek",
        "Kalůsek",
        "Ňajvětšej kreminálník",
        "Zloděj zlodějský",
        "Těn ožrala",
        "Padákový zabiják",
        "Viník našich posraných životů"
      ]
    },
    "2": {
      "matches": [
        "Kalouska",
        "Miroslava Kalouska"
      ],
      "replacements": [
        "Arcikacíře Mirka",
        "Kalůska",
        "Ňajvětšeho kreminálníka",
        "Zloděje zlodějského",
        "Těho ožraly",
        "Padákového zabijáka",
        "Viníka našich posraných životů"
      ]
    },
    "3": {
      "matches": [
        "Kalouskovi",
        "Miroslavu Kalouskovi"
      ],
      "replacements": [
        "Arcikacíři Mirkovi",
        "Kalůskovi",
        "Ňajvětšemu kreminálníkovi",
        "Zloději zlodějskému",
        "Těmu ožralovi",
        "Padákovému zabijákovi",
        "Viníku našich posraných životů"
      ]
    },
    "4": {
      "matches": [
        "Kalouska",
        "Miroslava Kalouska"
      ],
      "replacements": [
        "Arcikacíře Mirka",
        "Kalůska",
        "Ňajvětšeho kreminálníka",
        "Zloděje zlodějského",
        "Těho ožralu",
        "Padákového zabijáka",
        "Viníka našich posraných životů"
      ]
    },
    "5": {
      "matches": [
        "Kalousku",
        "Miroslave Kalousku"
      ],
      "replacements": [
        "Arcikacíři Mirku",
        "Kalůsku",
        "Ňajvětšej kreminálníku",
        "Zloději zlodějský",
        "Ty ožralo",
        "Padákový zabijáku",
        "Viníku našich posraných životů"
      ]
    },
    "6": {
      "matches": [
        "Kalouskovi",
        "Miroslavu Kalouskovi"
      ],
      "replacements": [
        "Arcikacíři Mirkovi",
        "Kalůskovi",
        "Ňajvětšemu kreminálníkovi",
        "Zloději zlodějském",
        "Ťom ožralovi",
        "Padákovém zabijákovi",
        "Viníku našich posraných životů"
      ]
    },
    "7": {
      "matches": [
        "Kalouskem",
        "Miroslavem Kalouskem"
      ],
      "replacements": [
        "Arcikacířem Mirkem",
        "Kalůskem",
        "Ňajvětšejm kreminálníkem",
        "Zlodějem zlodějským",
        "Tím ožralou",
        "Padákovým zabijákem",
        "Viníkem našich posraných životů"
      ]
    }
  },
  "adjectives": {
    "to": {
      "matches": [
        "Kalouskovo"
      ],
      "replacements": [
        "Kalůskovo",
        "Ožralovo"
      ]
    },
    "ta": {
      "matches": [
        "Kalouskova"
      ],
      "replacements": [
        "Kalůskova",
        "Ožralova"
      ]
    },
    "ten": {
      "matches": [
        "Kalouskův"
      ],
      "replacements": [
        "Kalůskův",
        "Ožralův"
      ]
    },
    "ti": {
      "matches": [
        "Kalouskovi"
      ],
      "replacements": [
        "Kalůskovi",
        "Ožralovi"
      ]
    },
    "ty": {
      "matches": [
        "Kalouskovy"
      ],
      "replacements": [
        "Kalůskovy",
        "Ožralovy"
      ]
    },
    "te": {
      "matches": [
        "Kalouskově"
      ],
      "replacements": [
        "Kalůskově",
        "Ožralově"
      ]
    },
    "tu": {
      "matches": [
        "Kalouskovu"
      ],
      "replacements": [
        "Kalůskovu",
        "Ožralovu"
      ]
    },
    "tou": {
      "matches": [
        "Kalouskovou"
      ],
      "replacements": [
        "Kalůskovou",
        "Ožralovou"
      ]
    },
    "tim": {
      "matches": [
        "Kalouskovým"
      ],
      "replacements": [
        "Kalůskovým",
        "Ožralovým"
      ]
    },
    "tech": {
      "matches": [
        "Kalouskových"
      ],
      "replacements": [
        "Kalůskových",
        "Ožralových"
      ]
    },
    "temi": {
      "matches": [
        "Kalouskovými"
      ],
      "replacements": [
        "Kalůskovými",
        "Ožralovými"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/schillerova.json
{
  "name": "schillerova",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Schillerová",
        "Alena Schillerová"
      ],
      "replacements": [
        "Ministryně Instagramu",
        "Candy crush šampiónka",
        "Miss Gerontia",
        "Dluhový schodek",
        "Tiktok tanečnice",
        "Hranolka",
        "Dlužena"
      ]
    },
    "2": {
      "matches": [
        "Schillerové",
        "Aleny Schillerové"
      ],
      "replacements": [
        "Ministryně Instagramu",
        "Candy crush šampiónky",
        "Miss Gerontie",
        "Dluhového schodku",
        "Tiktok tanečnice",
        "Hranolky",
        "Dluženy"
      ]
    },
    "3": {
      "matches": [
        "Schillerové",
        "Aleně Schillerové"
      ],
      "replacements": [
        "Ministryni Instagramu",
        "Candy crush šampiónce",
        "Miss Gerontii",
        "Dluhovému schodku",
        "Tiktok tanečnici",
        "Hranolce",
        "Dluženě"
      ]
    },
    "4": {
      "matches": [
        "Schillerovou",
        "Alenu Schillerovou"
      ],
      "replacements": [
        "Ministryni Instagramu",
        "Candy crush šampiónku",
        "Miss Gerontii",
        "Dluhový schodek",
        "Tiktok tanečnici",
        "Hranolku",
        "Dluženu"
      ]
    },
    "5": {
      "matches": [
        "Schillerová",
        "Aleno Schillerová"
      ],
      "replacements": [
        "Ministryně Instagramu",
        "Candy crush šampiónko",
        "Miss Gerontie",
        "Dluhový schodku",
        "Tiktok tanečnice",
        "Hranolko",
        "Dluženo"
      ]
    },
    "6": {
      "matches": [
        "Schillerové",
        "Aleně Schillerové"
      ],
      "replacements": [
        "Ministryni Instagramu",
        "Candy crush šampiónce",
        "Miss Gerontii",
        "Dluhovém schodku",
        "Tiktok tanečnici",
        "Hranolce",
        "Dluženě"
      ]
    },
    "7": {
      "matches": [
        "Schillerovou",
        "Alenou Schillerovou"
      ],
      "replacements": [
        "Ministryní Instagramu",
        "Candy crush šampiónkou",
        "Miss Gerontií",
        "Dluhovým schodkem",
        "Tiktok tanečnicí",
        "Hranolkou",
        "Dluženou"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/nacher.json
{
  "name": "nacher",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Nacher",
        "Patrik Nacher"
      ],
      "replacements": [
        "Krysí žokej",
        "Leprikón",
        "Jeho maličkost osobně",
        "Pražský krysařík",
        "Hobit",
        "Sádrový trpaslík",
        "Schumacher z angličáku"
      ]
    },
    "2": {
      "matches": [
        "Nachera",
        "Patrika Nachera"
      ],
      "replacements": [
        "Krysího žokeje",
        "Leprikóna",
        "Jeho maličkosti osobně",
        "Pražského krysaříka",
        "Hobita",
        "Sádrového trpaslíka",
        "Schumachera z angličáku"
      ]
    },
    "3": {
      "matches": [
        "Nacherovi",
        "Patriku Nacherovi"
      ],
      "replacements": [
        "Krysímu žokejovi",
        "Leprikónovi",
        "Jeho maličkosti osobně",
        "Pražskému krysaříkovi",
        "Hobitovi",
        "Sádrovému trpaslíkovi",
        "Schumacherovi z angličáku"
      ]
    },
    "4": {
      "matches": [
        "Nachera",
        "Patrika Nachera"
      ],
      "replacements": [
        "Krysího žokeje",
        "Leprikóna",
        "Jeho maličkost osobně",
        "Pražského krysaříka",
        "Hobita",
        "Sádrového trpaslíka",
        "Schumachera z angličáku"
      ]
    },
    "5": {
      "matches": [
        "Nachere",
        "Patriku Nachere"
      ],
      "replacements": [
        "Krysí žokeji",
        "Leprikóne",
        "Vaše maličkosti osobně",
        "Pražský krysaříku",
        "Hobite",
        "Sádrový trpaslíku",
        "Schumachere z angličáku"
      ]
    },
    "6": {
      "matches": [
        "Nacherovi",
        "Patriku Nacherovi"
      ],
      "replacements": [
        "Krysím žokejovi",
        "Leprikónovi",
        "Jeho maličkosti osobně",
        "Pražském krysaříkovi",
        "Hobitovi",
        "Sádrovém trpaslíkovi",
        "Schumacherovi z angličáku"
      ]
    },
    "7": {
      "matches": [
        "Nacherem",
        "Patrikem Nacherem"
      ],
      "replacements": [
        "Krysím žokejem",
        "Leprikónem",
        "Jeho maličkostí osobně",
        "Pražským krysaříkem",
        "Hobitem",
        "Sádrovým trpaslíkem",
        "Schumacherem z angličáku"
      ]
    }
  },
  "adjectives": {
    "to": {
      "matches": [
        "Nacherovo"
      ],
      "replacements": [
        "Leprikónovo",
        "Krysaříkovo",
        "Hobitovo",
        "Trpaslíkovo"
      ]
    },
    "ta": {
      "matches": [
        "Nacherova"
      ],
      "replacements": [
        "Leprikónova",
        "Krysaříkova",
        "Hobitova",
        "Trpaslíkova"
      ]
    },
    "ten": {
      "matches": [
        "Nacherův"
      ],
      "replacements": [
        "Leprikónův",
        "Krysaříkův",
        "Hobitův",
        "Trpaslíkův"
      ]
    },
    "ti": {
      "matches": [
        "Nacherovi"
      ],
      "replacements": [
        "Leprikónovi",
        "Krysaříkovi",
        "Hobitovi",
        "Trpaslíkovi"
      ]
    },
    "ty": {
      "matches": [
        "Nacherovy"
      ],
      "replacements": [
        "Leprikónovy",
        "Krysaříkovy",
        "Hobitovy",
        "Trpaslíkovy"
      ]
    },
    "te": {
      "matches": [
        "Nacherově"
      ],
      "replacements": [
        "Leprikónově",
        "Krysaříkově",
        "Hobitově",
        "Trpaslíkově"
      ]
    },
    "tu": {
      "matches": [
        "Nacherovu"
      ],
      "replacements": [
        "Leprikónovu",
        "Krysaříkovu",
        "Hobitovu",
        "Trpaslíkovu"
      ]
    },
    "tou": {
      "matches": [
        "Nacherovou"
      ],
      "replacements": [
        "Leprikónovou",
        "Krysaříkovou",
        "Hobitovou",
        "Trpaslíkovou"
      ]
    },
    "tim": {
      "matches": [
        "Nacherovým"
      ],
      "replacements": [
        "Leprikónovým",
        "Krysaříkovým",
        "Hobitovým",
        "Trpaslíkovým"
      ]
    },
    "tech": {
      "matches": [
        "Nacherových"
      ],
      "replacements": [
        "Leprikónových",
        "Krysaříkových",
        "Hobitových",
        "Trpaslíkových"
      ]
    },
    "temi": {
      "matches": [
        "Nacherovými"
      ],
      "replacements": [
        "Leprikónovými",
        "Krysaříkovými",
        "Hobitovými",
        "Trpaslíkovými"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/other-sources/microslop/items/ai.json
{
  "name": "ai",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Artificial Intelligence"
      ],
      "replacements": [
        "Actually Indians"
      ]
    },
    "2": {
      "matches": [],
      "replacements": []
    },
    "3": {
      "matches": [],
      "replacements": []
    },
    "4": {
      "matches": [],
      "replacements": []
    },
    "5": {
      "matches": [],
      "replacements": []
    },
    "6": {
      "matches": [],
      "replacements": []
    },
    "7": {
      "matches": [],
      "replacements": []
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/stastny.json
{
  "name": "stastny",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Boris Šťastný",
        "Šťastný"
      ],
      "replacements": [
        "Ministr kotrmelců",
        "s ministerstvem Šťastný",
        "Ve výtahu neŠťastný"
      ]
    },
    "2": {
      "matches": [
        "Borise Šťastného",
        "Šťastného"
      ],
      "replacements": [
        "Ministra kotrmelců",
        "s ministerstvem Šťastného",
        "Ve výtahu neŠťastného"
      ]
    },
    "3": {
      "matches": [
        "Borisi Šťastnému",
        "Šťastnému"
      ],
      "replacements": [
        "Ministrovi kotrmelců",
        "s ministerstvem Šťastnému",
        "Ve výtahu neŠťastnému"
      ]
    },
    "4": {
      "matches": [
        "Borise Šťastného",
        "Šťastného"
      ],
      "replacements": [
        "Ministra kotrmelců",
        "s ministerstvem Šťastného",
        "Ve výtahu neŠťastného"
      ]
    },
    "5": {
      "matches": [
        "Borisi Šťastný",
        "Šťastný"
      ],
      "replacements": [
        "Ministro kotrmelců",
        "s ministerstvem Šťastný",
        "Ve výtahu neŠťastný"
      ]
    },
    "6": {
      "matches": [
        "Borisi Šťastném",
        "Šťastném"
      ],
      "replacements": [
        "Ministrovi kotrmelců",
        "s ministerstvem Šťastném",
        "Ve výtahu neŠťastném"
      ]
    },
    "7": {
      "matches": [
        "Borisem Šťastným",
        "Šťastným"
      ],
      "replacements": [
        "Ministrem kotrmelců",
        "s ministerstvem Šťastným",
        "Ve výtahu neŠťastným"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/feri.json
{
  "name": "feri",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Feri",
        "Dominik Feri"
      ],
      "replacements": [
        "Úplně nahej",
        "Predátor z Teplic",
        "Ten co neuhne"
      ]
    },
    "2": {
      "matches": [
        "Feriho",
        "Dominika Feriho"
      ],
      "replacements": [
        "Úplně nahýho",
        "Predátora z Teplic",
        "Toho co neuhne"
      ]
    },
    "3": {
      "matches": [
        "Ferihomu",
        "Dominiku Ferihomu"
      ],
      "replacements": [
        "Úplně nahýmu",
        "Predátorovi z Teplic",
        "Tomu co neuhne"
      ]
    },
    "4": {
      "matches": [
        "Feriho",
        "Dominika Feriho"
      ],
      "replacements": [
        "Úplně nahýho",
        "Predátora z Teplic",
        "Toho co neuhne"
      ]
    },
    "5": {
      "matches": [
        "Feri",
        "Dominiku Feri"
      ],
      "replacements": [
        "Úplně nahej",
        "Predátore z Teplic",
        "Ty co neuhneš"
      ]
    },
    "6": {
      "matches": [
        "Ferihom",
        "Dominiku Ferihom"
      ],
      "replacements": [
        "Úplně nahým",
        "Predátorovi z Teplic",
        "Tom co neuhne"
      ]
    },
    "7": {
      "matches": [
        "Ferihom",
        "Dominikem Ferihom"
      ],
      "replacements": [
        "Úplně nahým",
        "Predátorem z Teplic",
        "Tím co neuhne"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/topolanek.json
{
  "name": "topolanek",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Topolánek",
        "Mirek Topolánek"
      ],
      "replacements": [
        "Buran po Toskánsku",
        "Dalíkova amnestie",
        "Švédská trojka"
      ]
    },
    "2": {
      "matches": [
        "Topolánka",
        "Mirka Topolánka"
      ],
      "replacements": [
        "Burana po Toskánsku",
        "Dalíkovy amnestie",
        "Švédské trojky"
      ]
    },
    "3": {
      "matches": [
        "Topolánkovi",
        "Mirkovi Topolánkovi"
      ],
      "replacements": [
        "Buranovi po Toskánsku",
        "Dalíkově amnestii",
        "Švédské trojce"
      ]
    },
    "4": {
      "matches": [
        "Topolánka",
        "Mirka Topolánka"
      ],
      "replacements": [
        "Burana po Toskánsku",
        "Dalíkovu amnestii",
        "Švédskou trojku"
      ]
    },
    "5": {
      "matches": [
        "Topolánku",
        "Mirku Topolánku"
      ],
      "replacements": [
        "Burane po Toskánsku",
        "Dalíkova amnestie",
        "Švédská trojko"
      ]
    },
    "6": {
      "matches": [
        "Topolánkovi",
        "Mirkovi Topolánkovi"
      ],
      "replacements": [
        "Buranovi po Toskánsku",
        "Dalíkově amnestii",
        "Švédské trojce"
      ]
    },
    "7": {
      "matches": [
        "Topolánkem",
        "Mirkem Topolánkem"
      ],
      "replacements": [
        "Buranem po Toskánsku",
        "Dalíkovou amnestií",
        "Švédskou trojkou"
      ]
    }
  }
}
