=== dlabaja/MrtkiBlockReloaded/data/item.schema.json
{
  "definitions": {
    "declension": {
      "type": "object",
      "properties": {
        "matches": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "replacements": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["matches", "replacements"]
    }
  },
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "ID skupiny"
    },
    "matchUpperCase": {
      "type": "boolean",
      "description": "True pokud mají být matchovány i matche psané velkými písmeny (Babiš -> BABIŠ)"
    },
    "matchLowerCase": {
      "type": "boolean",
      "description": "True pokud mají být matchovány i matche psané malými písmeny (Babiš -> babiš)"
    },
    "cases": {
      "type": "object",
      "properties": {
        "1": {"$ref": "#/definitions/declension"},
        "2": {"$ref": "#/definitions/declension"},
        "3": {"$ref": "#/definitions/declension"},
        "4": {"$ref": "#/definitions/declension"},
        "5": {"$ref": "#/definitions/declension"},
        "6": {"$ref": "#/definitions/declension"},
        "7": {"$ref": "#/definitions/declension"}
      },
      "required": ["1", "2", "3", "4", "5", "6", "7"]
    },
    "adjectives": {
      "type": "object",
      "properties": {
        "to": {"$ref": "#/definitions/declension"},
        "ta": {"$ref": "#/definitions/declension"},
        "ten": {"$ref": "#/definitions/declension"},
        "ti": {"$ref": "#/definitions/declension"},
        "ty": {"$ref": "#/definitions/declension"},
        "te": {"$ref": "#/definitions/declension"},
        "tu": {"$ref": "#/definitions/declension"},
        "tou": {"$ref": "#/definitions/declension"},
        "tim": {"$ref": "#/definitions/declension"},
        "tech": {"$ref": "#/definitions/declension"},
        "temi": {"$ref": "#/definitions/declension"}
      },
      "required": ["to", "ta", "ten", "ti", "ty", "te", "tu", "tou", "tim", "tech", "temi"]
    }
  },
  "required": ["name", "matchUpperCase", "matchLowerCase", "cases"]
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/ovcacek.json
{
  "name": "ovcacek",
  "matchUpperCase": true,
  "matchLowerCase": false,
  "cases": {
    "1": {
      "matches": [
        "Ovčáček",
        "Jiří Ovčáček"
      ],
      "replacements": [
        "Buzerant s kabelkou",
        "Zaměstnanec hospicu Lány",
        "Twitterový terrorista"
      ]
    },
    "2": {
      "matches": [
        "Ovčáčka",
        "Jiřího Ovčáčka"
      ],
      "replacements": [
        "Buzeranta s kabelkou",
        "Zaměstnance hospicu Lány",
        "Twitterového terroristy"
      ]
    },
    "3": {
      "matches": [
        "Ovčáčkovi",
        "Jiřímu Ovčáčkovi"
      ],
      "replacements": [
        "Buzerantovi s kabelkou",
        "Zaměstnanci hospicu Lány",
        "Twitterovému terroristovi"
      ]
    },
    "4": {
      "matches": [
        "Ovčáčka",
        "Jiřího Ovčáčka"
      ],
      "replacements": [
        "Buzeranta s kabelkou",
        "Zaměstnance hospicu Lány",
        "Twitterového terroristu"
      ]
    },
    "5": {
      "matches": [
        "Ovčáčku",
        "Jiří Ovčáčku"
      ],
      "replacements": [
        "Buzerante s kabelkou",
        "Zaměstnanče hospicu Lány",
        "Twitterový terroristo"
      ]
    },
    "6": {
      "matches": [
        "Ovčáčkovi",
        "Jiřím Ovčáčkovi"
      ],
      "replacements": [
        "Buzerantovi s kabelkou",
        "Zaměstnanci hospicu Lány",
        "Twitterovém terroristovi"
      ]
    },
    "7": {
      "matches": [
        "Ovčáčkem",
        "Jiřím Ovčáčkem"
      ],
      "replacements": [
        "Buzerantem s kabelkou",
        "Zaměstnancem hospicu Lány",
        "Twitterovým terroristou"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/osobnosti/cz/xaver.json
{
  "name": "vesely",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Luboš Xaver Veselý",
        "Luboš Veselý",
        "Xaver",
        "Xaver Veselý",
        "Luboš „Xaver“ Veselý",
        "Luboš \"Xaver\" Veselý"
      ],
      "replacements": [
        "Vypasená svině",
        "Ruský nok",
        "Ředitel gulagu",
        "Strůjce genocidy chlebíčků",
        "Postrach oleje z friťáku",
        "Otesánek z televize",
        "Blop"
      ]
    },
    "2": {
      "matches": [
        "Luboše Xavera Veselého",
        "Luboše Veselého",
        "Xavera",
        "Xavera Veselého",
        "Luboše „Xavera“ Veselého",
        "Luboše \"Xavera\" Veselého"
      ],
      "replacements": [
        "Vypasené svině",
        "Ruského noku",
        "Ředitele gulagu",
        "Strůjce genocidy chlebíčků",
        "Postracha oleje z friťáku",
        "Otesánka z televize",
        "Blopa"
      ]
    },
    "3": {
      "matches": [
        "Luboši Xaveru Veselému",
        "Luboši Veselému",
        "Xaverovi",
        "Xaverovi Veselému",
        "Luboši „Xaveru“ Veselému",
        "Luboši \"Xaveru\" Veselému"
      ],
      "replacements": [
        "Vypasené svini",
        "Ruskému noku",
        "Řediteli gulagu",
        "Strůjci genocidy chlebíčků",
        "Postrachu oleje z friťáku",
        "Otesánkovi z televize",
        "Blopovi"
      ]
    },
    "4": {
      "matches": [
        "Luboše Xavera Veselého",
        "Luboše Veselého",
        "Xavera",
        "Xavera Veselého",
        "Luboše „Xavera“ Veselého",
        "Luboše \"Xavera\" Veselého"
      ],
      "replacements": [
        "Vypasenou svini",
        "Ruského noka",
        "Ředitele gulagu",
        "Strůjce genocidy chlebíčků",
        "Postracha oleje z friťáku",
        "Otesánka z televize",
        "Blopa"
      ]
    },
    "5": {
      "matches": [
        "Luboši Xavere Veselý",
        "Luboši Veselý",
        "Xavore",
        "Xavere Veselý",
        "Luboši „Xavere“ Veselý",
        "Luboši \"Xavere\" Veselý"
      ],
      "replacements": [
        "Vypasená svině",
        "Ruský noku",
        "Řediteli gulagu",
        "Strůjce genocidy chlebíčků",
        "Postrachu oleje z friťáku",
        "Otesánku z televize",
        "Blope"
      ]
    },
    "6": {
      "matches": [
        "Luboši Xaveru Veselém",
        "Luboši Veselém",
        "Xaverovi",
        "Xaveru Veselém",
        "Luboši „Xaveru“ Veselém",
        "Luboši \"Xaveru\" Veselém"
      ],
      "replacements": [
        "Vypasené svini",
        "Ruském noku",
        "Řediteli gulagu",
        "Strůjci genocidy chlebíčků",
        "Postrachu oleje z friťáku",
        "Otesánkovi z televize",
        "Blopovi"
      ]
    },
    "7": {
      "matches": [
        "Lubošem Xaverem Veselým",
        "Lubošem Veselým",
        "Xaverem",
        "Xaverem Veselým",
        "Lubošem „Xaverem“ Veselým",
        "Lubošem \"Xaverem\" Veselým"
      ],
      "replacements": [
        "Vypasenou sviní",
        "Ruským nokem",
        "Ředitelem gulagu",
        "Strůjcem genocidy chlebíčků",
        "Postrachem oleje z friťáku",
        "Otesánkem z televize",
        "Blopem"
      ]
    }
  },
  "adjectives": {
    "to": {
      "matches": [
        "Xaverovo"
      ],
      "replacements": [
        "Otesánkovo",
        "Blopovo"
      ]
    },
    "ta": {
      "matches": [
        "Xaverova"
      ],
      "replacements": [
        "Otesánkova",
        "Blopova"
      ]
    },
    "ten": {
      "matches": [
        "Xaverův"
      ],
      "replacements": [
        "Otesánkův",
        "Blopův"
      ]
    },
    "ti": {
      "matches": [
        "Xaverovi"
      ],
      "replacements": [
        "Otesánkovi",
        "Blopovi"
      ]
    },
    "ty": {
      "matches": [
        "Xaverovy"
      ],
      "replacements": [
        "Otesánkovy",
        "Blopovy"
      ]
    },
    "te": {
      "matches": [
        "Xaverově"
      ],
      "replacements": [
        "Otesánkově",
        "Blopově"
      ]
    },
    "tu": {
      "matches": [
        "Xaverovu"
      ],
      "replacements": [
        "Otesánkovu",
        "Blopovu"
      ]
    },
    "tou": {
      "matches": [
        "Xaverovou"
      ],
      "replacements": [
        "Otesánkovou",
        "Blopovou"
      ]
    },
    "tim": {
      "matches": [
        "Xaverovým"
      ],
      "replacements": [
        "Otesánkovým",
        "Blopovým"
      ]
    },
    "tech": {
      "matches": [
        "Xaverových"
      ],
      "replacements": [
        "Otesánkových",
        "Blopových"
      ]
    },
    "temi": {
      "matches": [
        "Xaverovými"
      ],
      "replacements": [
        "Otesánkovými",
        "Blopovými"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/osobnosti/cz/soukup.json
{
  "name": "soukup",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Soukup",
        "Jaromír Soukup"
      ],
      "replacements": [
        "Větroplach",
        "Debatér sám se sebou",
        "Dvouprocentní premiér",
        "Oportunistická svině",
        "Majitel největší čínské investice v ČR",
        "Hvězda ČSFD"
      ]
    },
    "2": {
      "matches": [
        "Soukupa",
        "Jaromíra Soukupa"
      ],
      "replacements": [
        "Větroplacha",
        "Debatéra sama se sebou",
        "Dvouprocentního premiéra",
        "Oportunistické svině",
        "Majitele největší čínské investice v ČR",
        "Hvězdy ČSFD"
      ]
    },
    "3": {
      "matches": [
        "Soukupovi",
        "Jaromíru Soukupovi"
      ],
      "replacements": [
        "Větroplachovi",
        "Debatérovi sám se sebou",
        "Dvouprocentnímu premiérovi",
        "Oportunistické svini",
        "Majiteli největší čínské investice v ČR",
        "Hvězdě ČSFD"
      ]
    },
    "4": {
      "matches": [
        "Soukupa",
        "Jaromíra Soukupa"
      ],
      "replacements": [
        "Větroplacha",
        "Debatéra sama se sebou",
        "Dvouprocentního premiéra",
        "Oportunistickou svini",
        "Majitele největší čínské investice v ČR",
        "Hvězdu ČSFD"
      ]
    },
    "5": {
      "matches": [
        "Soukupe",
        "Jaromíre Soukupe"
      ],
      "replacements": [
        "Větroplachu",
        "Debatére sám se sebou",
        "Dvouprocentní premiére",
        "Oportunistická svině",
        "Majiteli největší čínské investice v ČR",
        "Hvězdo ČSFD"
      ]
    },
    "6": {
      "matches": [
        "Soukupovi",
        "Jaromíru Soukupovi"
      ],
      "replacements": [
        "Větroplachovi",
        "Debatérovi sám se sebou",
        "Dvouprocentním premiérovi",
        "Oportunistické svini",
        "Majiteli největší čínské investice v ČR",
        "Hvězdě ČSFD"
      ]
    },
    "7": {
      "matches": [
        "Soukupem",
        "Jaromírem Soukupem"
      ],
      "replacements": [
        "Větroplachem",
        "Debatérem sám se sebou",
        "Dvouprocentním premiérem",
        "Oportunistickou sviní",
        "Majitelem největší čínské investice v ČR",
        "Hvězdou ČSFD"
      ]
    }
  },
  "adjectives": {
    "to": {
      "matches": [
        "Soukupovo"
      ],
      "replacements": [
        "Větroplachovo",
        "Oportunistovo"
      ]
    },
    "ta": {
      "matches": [
        "Soukupova"
      ],
      "replacements": [
        "Větroplachova",
        "Oportunistova"
      ]
    },
    "ten": {
      "matches": [
        "Soukupův"
      ],
      "replacements": [
        "Větroplachův",
        "Oportunistův"
      ]
    },
    "ti": {
      "matches": [
        "Soukupovi"
      ],
      "replacements": [
        "Větroplachovi",
        "Oportunistovi"
      ]
    },
    "ty": {
      "matches": [
        "Soukupovy"
      ],
      "replacements": [
        "Větroplachovy",
        "Oportunistovy"
      ]
    },
    "te": {
      "matches": [
        "Soukupově"
      ],
      "replacements": [
        "Větroplachově",
        "Oportunistově"
      ]
    },
    "tu": {
      "matches": [
        "Soukupovu"
      ],
      "replacements": [
        "Větroplachovu",
        "Oportunistovu"
      ]
    },
    "tou": {
      "matches": [
        "Soukupovou"
      ],
      "replacements": [
        "Větroplachovou",
        "Oportunistovou"
      ]
    },
    "tim": {
      "matches": [
        "Soukupovým"
      ],
      "replacements": [
        "Větroplachovým",
        "Oportunistovým"
      ]
    },
    "tech": {
      "matches": [
        "Soukupových"
      ],
      "replacements": [
        "Větroplachových",
        "Oportunistových"
      ]
    },
    "temi": {
      "matches": [
        "Soukupovými"
      ],
      "replacements": [
        "Větroplachovými",
        "Oportunistovými"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/other-sources/microslop/items/genai.json
{
  "name": "genai",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Generative AI",
        "Gen AI"
      ],
      "replacements": [
        "Degenerative AI",
        "Degen AI"
      ]
    },
    "2": {
      "matches": [],
      "replacements": []
    },
    "3": {
      "matches": [],
      "replacements": []
    },
    "4": {
      "matches": [],
      "replacements": []
    },
    "5": {
      "matches": [],
      "replacements": []
    },
    "6": {
      "matches": [],
      "replacements": []
    },
    "7": {
      "matches": [],
      "replacements": []
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/other-sources/microslop/items/umela-inteligence.json
{
  "name": "umela-inteligence",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Umělá inteligence"
      ],
      "replacements": [
        "Umělá demence",
        "Umělá slopteligence"
      ]
    },
    "2": {
      "matches": [
        "Umělé inteligence"
      ],
      "replacements": [
        "Umělé demence",
        "Umělé slopteligence"
      ]
    },
    "3": {
      "matches": [
        "Umělé inteligenci"
      ],
      "replacements": [
        "Umělé demenci",
        "Umělé slopteligenci"
      ]
    },
    "4": {
      "matches": [
        "Umělou inteligenci"
      ],
      "replacements": [
        "Umělou demenci",
        "Umělou slopteligenci"
      ]
    },
    "5": {
      "matches": [
        "Umělá inteligence"
      ],
      "replacements": [
        "Umělá demence",
        "Umělá slopteligence"
      ]
    },
    "6": {
      "matches": [
        "Umělé inteligenci"
      ],
      "replacements": [
        "Umělé demenci",
        "Umělé slopteligenci"
      ]
    },
    "7": {
      "matches": [
        "Umělou inteligencí"
      ],
      "replacements": [
        "Umělou demencí",
        "Umělou slopteligencí"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/fiala.json
{
  "name": "fiala",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Fiala",
        "Petr Fiala"
      ],
      "replacements": [
        "Psí suchar",
        "Ztělesnění nudy",
        "Reklama na Ferrero",
        "Profesor \"Jedu poprvé na eskalátoru\"",
        "Skejťák v saku",
        "Petr Piala",
        "6-7 piv",
        "\"My neseme Staropramen\""
      ]
    },
    "2": {
      "matches": [
        "Fialy",
        "Petra Fialy"
      ],
      "replacements": [
        "Psího suchara",
        "Ztělesnění nudy",
        "Reklamy na Ferrero",
        "Profesora \"Jedu poprvé na eskalátoru\"",
        "Skejťáka v saku",
        "Petra Pialy",
        "6-7 piv",
        "\"My neseme Staropramen\""
      ]
    },
    "3": {
      "matches": [
        "Fialovi",
        "Petru Fialovi",
        "Petrovi Fialovi"
      ],
      "replacements": [
        "Psímu sucharovi",
        "Ztělesnění nudy",
        "Reklamě na Ferrero",
        "Profesorovi \"Jedu poprvé na eskalátoru\"",
        "Skejťákovi v saku",
        "Petru Pialovi",
        "6-7 piv",
        "\"My neseme Staropramen\""
      ]
    },
    "4": {
      "matches": [
        "Fialu",
        "Petra Fialu"
      ],
      "replacements": [
        "Psího suchara",
        "Ztělesnění nudy",
        "Reklamu na Ferrero",
        "Profesora \"Jedu poprvé na eskalátoru\"",
        "Skejťáka v saku",
        "Petra Pialu",
        "6-7 piv",
        "\"My neseme Staropramen\""
      ]
    },
    "5": {
      "matches": [
        "Fialo",
        "Petře Fialo"
      ],
      "replacements": [
        "Psí suchare",
        "Ztělesnění nudy",
        "Reklamo na Ferrero",
        "Profesore \"Jedu poprvé na eskalátoru\"",
        "Skejťáku v saku",
        "Petře Pialo",
        "6-7 piv",
        "\"My neseme Staropramen\""
      ]
    },
    "6": {
      "matches": [
        "Fialovi",
        "Petru Fialovi",
        "Petrovi Fialovi"
      ],
      "replacements": [
        "Psím sucharovi",
        "Ztělesnění nudy",
        "Reklamě na Ferrero",
        "Profesorovi \"Jedu poprvé na eskalátoru\"",
        "Skejťákovi v saku",
        "Petru Pialovi",
        "6-7 piv",
        "\"My neseme Staropramen\""
      ]
    },
    "7": {
      "matches": [
        "Fialou",
        "Petrem Fialou"
      ],
      "replacements": [
        "Psím sucharem",
        "Ztělesněním nudy",
        "Reklamou na Ferrero",
        "Profesorem \"Jedu poprvé na eskalátoru\"",
        "Skejťákem v saku",
        "Petrem Pialou",
        "6-7 piv",
        "\"My neseme Staropramen\""
      ]
    }
  },
  "adjectives": {
    "to": {
      "matches": [
        "Fialovo"
      ],
      "replacements": [
        "Sucharovo",
        "Nutellovo",
        "Skejťákovo",
        "Pialovo"
      ]
    },
    "ta": {
      "matches": [
        "Fialova"
      ],
      "replacements": [
        "Sucharova",
        "Nutellova",
        "Skejťákova",
        "Pialova"
      ]
    },
    "ten": {
      "matches": [
        "Fialův"
      ],
      "replacements": [
        "Sucharův",
        "Nutellův",
        "Skejťákův",
        "Pialův"
      ]
    },
    "ti": {
      "matches": [
        "Fialovi"
      ],
      "replacements": [
        "Sucharovi",
        "Nutellovi",
        "Skejťákovi",
        "Pialovi"
      ]
    },
    "ty": {
      "matches": [
        "Fialovy"
      ],
      "replacements": [
        "Sucharovy",
        "Nutellovy",
        "Skejťákovy",
        "Pialovy"
      ]
    },
    "te": {
      "matches": [
        "Fialově"
      ],
      "replacements": [
        "Sucharově",
        "Nutellově",
        "Skejťákově",
        "Pialově"
      ]
    },
    "tu": {
      "matches": [
        "Fialovu"
      ],
      "replacements": [
        "Sucharovu",
        "Nutellovu",
        "Skejťákovu",
        "Pialovu"
      ]
    },
    "tou": {
      "matches": [
        "Fialovou"
      ],
      "replacements": [
        "Sucharovou",
        "Nutellovou",
        "Skejťákovou",
        "Pialovou"
      ]
    },
    "tim": {
      "matches": [
        "Fialovým"
      ],
      "replacements": [
        "Sucharovým",
        "Nutellovým",
        "Skejťákovým",
        "Pialovým"
      ]
    },
    "tech": {
      "matches": [
        "Fialových"
      ],
      "replacements": [
        "Sucharových",
        "Nutellových",
        "Skejťákových",
        "Pialových"
      ]
    },
    "temi": {
      "matches": [
        "Fialovými"
      ],
      "replacements": [
        "Sucharovými",
        "Nutellovými",
        "Skejťákovými",
        "Pialovými"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/macinka-long.json
{
  "name": "macinka-long",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Petr Macinka"
      ],
      "replacements": [
        "Metr Pacinka",
        "Petr Prcinka",
        "Petr Micinka",
        "Petr Nacinka"
      ]
    },
    "2": {
      "matches": [
        "Petra Macinky"
      ],
      "replacements": [
        "Metra Pacinky",
        "Petra Prcinky",
        "Petra Micinky",
        "Petra Nacinky"
      ]
    },
    "3": {
      "matches": [
        "Petru Macinkovi"
      ],
      "replacements": [
        "Metru Pacinkovi",
        "Petru Prcinkovi",
        "Petru Micinkovi",
        "Petru Nacinkovi"
      ]
    },
    "4": {
      "matches": [
        "Petra Macinku"
      ],
      "replacements": [
        "Metra Pacinku",
        "Petra Prcinku",
        "Petra Micinku",
        "Petra Nacinku"
      ]
    },
    "5": {
      "matches": [
        "Petře Macinko"
      ],
      "replacements": [
        "Metře Pacinko",
        "Petře Prcinko",
        "Petře Micinko",
        "Petře Nacinko"
      ]
    },
    "6": {
      "matches": [
        "Petru Macinkovi"
      ],
      "replacements": [
        "Metru Pacinkovi",
        "Petru Prcinkovi",
        "Petru Micinkovi",
        "Petru Nacinkovi"
      ]
    },
    "7": {
      "matches": [
        "Petrem Macinkou"
      ],
      "replacements": [
        "Metrem Pacinkou",
        "Petrem Prcinkou",
        "Petrem Micinkou",
        "Petrem Nacinkou"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/other-sources/microslop/data.json
[{"name":"ai","matchUpperCase":true,"matchLowerCase":true,"cases":{"1":{"matches":["Artificial Intelligence"],"replacements":["Actually Indians"]},"2":{"matches":[],"replacements":[]},"3":{"matches":[],"replacements":[]},"4":{"matches":[],"replacements":[]},"5":{"matches":[],"replacements":[]},"6":{"matches":[],"replacements":[]},"7":{"matches":[],"replacements":[]}}},{"name":"azure","matchUpperCase":true,"matchLowerCase":true,"cases":{"1":{"matches":["Azure"],"replacements":["Assure"]},"2":{"matches":[],"replacements":[]},"3":{"matches":[],"replacements":[]},"4":{"matches":[],"replacements":[]},"5":{"matches":[],"replacements":[]},"6":{"matches":[],"replacements":[]},"7":{"matches":[],"replacements":[]}}},{"name":"copilot","matchUpperCase":true,"matchLowerCase":true,"cases":{"1":{"matches":["Copilot"],"replacements":["Slopilot"]},"2":{"matches":["Copilotu","Copilota"],"replacements":["Slopilotu"]},"3":{"matches":["Copilotu","Copilotovi"],"replacements":["Slopilotu"]},"4":{"matches":["Copilot"],"replacements":["Slopilot"]},"5":{"matches":["Copilote"],"replacements":["Slopilote"]},"6":{"matches":["Copilotu","Copilotovi"],"replacements":["Slopilotu"]},"7":{"matches":["Copilotem"],"replacements":["Slopilotem"]}}},{"name":"gamepass","matchUpperCase":true,"matchLowerCase":true,"cases":{"1":{"matches":["Game Pass","Gamepass"],"replacements":["Gay Pass"]},"2":{"matches":[],"replacements":[]},"3":{"matches":[],"replacements":[]},"4":{"matches":[],"replacements":[]},"5":{"matches":[],"replacements":[]},"6":{"matches":[],"replacements":[]},"7":{"matches":[],"replacements":[]}}},{"name":"genai","matchUpperCase":true,"matchLowerCase":true,"cases":{"1":{"matches":["Generative AI","Gen AI"],"replacements":["Degenerative AI","Degen AI"]},"2":{"matches":[],"replacements":[]},"3":{"matches":[],"replacements":[]},"4":{"matches":[],"replacements":[]},"5":{"matches":[],"replacements":[]},"6":{"matches":[],"replacements":[]},"7":{"matches":[],"replacements":[]}}},{"name":"microsoft","matchUpperCase":true,"matchLowerCase":true,"cases":{"1":{"matches":["Microsoft"],"replacements":["Microslop","Macroslop"]},"2":{"matches":["Microsoftu"],"replacements":["Microslopu","Macroslopu"]},"3":{"matches":["Microsoftu"],"replacements":["Microslopu","Macroslopu"]},"4":{"matches":["Microsoft"],"replacements":["Microslop","Macroslop"]},"5":{"matches":["Microsofte"],"replacements":["Microslope","Macroslope"]},"6":{"matches":["Microsoftu","Microsoftě"],"replacements":["Microslopu","Macroslopu","Microslope","Macroslope"]},"7":{"matches":["Microsoftem"],"replacements":["Microslopem","Macroslopem"]}}},{"name":"nadella","matchUpperCase":true,"matchLowerCase":true,"cases":{"1":{"matches":["Satya Narayana Nadella","Satya Nadella","Nadella"],"replacements":["Slopya Nutella"]},"2":{"matches":["Satya Narayana Nadelly","Satya Nadelly","Nadelly"],"replacements":["Slopya Nutelly"]},"3":{"matches":["Satyu Narayana Nadellovi","Satyu Nadellovi","Nadellovi"],"replacements":["Slopyu Nutellovi"]},"4":{"matches":["Satyu Narayana Nadellu","Satyu Nadellu","Nadellu"],"replacements":["Slopyu Nutellu"]},"5":{"matches":["Satyo Narayana Nadello","Satyo Nadello","Nadello"],"replacements":["Slopyo Nutello"]},"6":{"matches":["Satyu Narayana Nadellovi","Satyu Nadellovi","Nadellovi"],"replacements":["Slopyu Nutellovi"]},"7":{"matches":["Satyem Narayana Nadellou","Satyem Nadellou","Nadellou"],"replacements":["Slopyem Nutellou"]}},"adjectives":{"to":{"matches":["Nadellovo"],"replacements":["Nutellovo"]},"ta":{"matches":["Nadellova"],"replacements":["Nutellova"]},"ten":{"matches":["Nadellův"],"replacements":["Nutellův"]},"ti":{"matches":["Nadellovi"],"replacements":["Nutellovi"]},"ty":{"matches":["Nadellovy"],"replacements":["Nutellovy"]},"te":{"matches":["Nadellově","Nadellové"],"replacements":["Nutellově","Nutellové"]},"tu":{"matches":["Nadellovu"],"replacements":["Nutellovu"]},"tou":{"matches":["Nadellovou"],"replacements":["Nutellovou"]},"tim":{"matches":["Nadellovým"],"replacements":["Nutellovým"]},"tech":{"matches":["Nadellových"],"replacements":["Nutellových"]},"temi":{"matches":["Nadellovými"],"replacements":["Nutellovými"]}}},{"name":"onedrive","matchUpperCase":true,"matchLowerCase":true,"cases":{"1":{"matches":["OneDrive","Onedrive"],"replacements":["CloudTumor"]},"2":{"matches":["OneDriveu","Onedriveu","OneDrivu","Onedrivu"],"replacements":["CloudTumoru"]},"3":{"matches":["OneDriveu","Onedriveu","OneDrivu","Onedrivu"],"replacements":["CloudTumoru"]},"4":{"matches":["OneDrive","Onedrive"],"replacements":["CloudTumor"]},"5":{"matches":["OneDrive","Onedrive"],"replacements":["CloudTumore"]},"6":{"matches":["OneDriveu","Onedriveu","OneDrivu","Onedrivu"],"replacements":["CloudTumoru"]},"7":{"matches":["Onedrivem","OneDrivem"],"replacements":["CloudTumorem"]}}},{"name":"windows","matchUpperCase":false,"matchLowerCase":false,"cases":{"1":{"matches":["Windows"],"replacements":["Cringedows","nejlepší Linux propaganda"]},"2":{"matches":["Windowsů"],"replacements":["Cringedowsů","nejlepší Linux propagandy"]},"3":{"matches":["Windowsům"],"replacements":["Cringedowsům","nejlepší Linux propagandě"]},"4":{"matches":["Windows"],"replacements":["Cringedows","nejlepší Linux propagandu"]},"5":{"matches":["Windows"],"replacements":["Cringedows","nejlepší Linux propagando"]},"6":{"matches":["Windowsech"],"replacements":["Cringedowsech","nejlepší Linux propagandě"]},"7":{"matches":["Windowsy"],"replacements":["Cringedowsy","nejlepší Linux propagandou"]}}},{"name":"xbox","matchUpperCase":true,"matchLowerCase":true,"cases":{"1":{"matches":["Xbox"],"replacements":["GreedYbox"]},"2":{"matches":["Xboxu"],"replacements":["GreedYboxu"]},"3":{"matches":["Xboxu"],"replacements":["GreedYboxu"]},"4":{"matches":["Xbox"],"replacements":["GreedYbox"]},"5":{"matches":["Xboxe"],"replacements":["GreedYboxe"]},"6":{"matches":["Xboxu"],"replacements":["GreedYboxu"]},"7":{"matches":["Xboxem"],"replacements":["GreedYboxem"]}}}]
