=== dlabaja/MrtkiBlockReloaded/data/item.schema.json
{
  "definitions": {
    "declension": {
      "type": "object",
      "properties": {
        "matches": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "replacements": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["matches", "replacements"]
    }
  },
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "ID skupiny"
    },
    "matchUpperCase": {
      "type": "boolean",
      "description": "True pokud mají být matchovány i matche psané velkými písmeny (Babiš -> BABIŠ)"
    },
    "matchLowerCase": {
      "type": "boolean",
      "description": "True pokud mají být matchovány i matche psané malými písmeny (Babiš -> babiš)"
    },
    "cases": {
      "type": "object",
      "properties": {
        "1": {"$ref": "#/definitions/declension"},
        "2": {"$ref": "#/definitions/declension"},
        "3": {"$ref": "#/definitions/declension"},
        "4": {"$ref": "#/definitions/declension"},
        "5": {"$ref": "#/definitions/declension"},
        "6": {"$ref": "#/definitions/declension"},
        "7": {"$ref": "#/definitions/declension"}
      },
      "required": ["1", "2", "3", "4", "5", "6", "7"]
    },
    "adjectives": {
      "type": "object",
      "properties": {
        "to": {"$ref": "#/definitions/declension"},
        "ta": {"$ref": "#/definitions/declension"},
        "ten": {"$ref": "#/definitions/declension"},
        "ti": {"$ref": "#/definitions/declension"},
        "ty": {"$ref": "#/definitions/declension"},
        "te": {"$ref": "#/definitions/declension"},
        "tu": {"$ref": "#/definitions/declension"},
        "tou": {"$ref": "#/definitions/declension"},
        "tim": {"$ref": "#/definitions/declension"},
        "tech": {"$ref": "#/definitions/declension"},
        "temi": {"$ref": "#/definitions/declension"}
      },
      "required": ["to", "ta", "ten", "ti", "ty", "te", "tu", "tou", "tim", "tech", "temi"]
    }
  },
  "required": ["name", "matchUpperCase", "matchLowerCase", "cases"]
}

=== dlabaja/MrtkiBlockReloaded/data/other-sources/microslop/items/copilot.json
{
  "name": "copilot",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Copilot"
      ],
      "replacements": [
        "Slopilot"
      ]
    },
    "2": {
      "matches": [
        "Copilotu",
        "Copilota"
      ],
      "replacements": [
        "Slopilotu"
      ]
    },
    "3": {
      "matches": [
        "Copilotu",
        "Copilotovi"
      ],
      "replacements": [
        "Slopilotu"
      ]
    },
    "4": {
      "matches": [
        "Copilot"
      ],
      "replacements": [
        "Slopilot"
      ]
    },
    "5": {
      "matches": [
        "Copilote"
      ],
      "replacements": [
        "Slopilote"
      ]
    },
    "6": {
      "matches": [
        "Copilotu",
        "Copilotovi"
      ],
      "replacements": [
        "Slopilotu"
      ]
    },
    "7": {
      "matches": [
        "Copilotem"
      ],
      "replacements": [
        "Slopilotem"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/other-sources/microslop/items/windows.json
{
  "name": "windows",
  "matchUpperCase": false,
  "matchLowerCase": false,
  "cases": {
    "1": {
      "matches": [
        "Windows"
      ],
      "replacements": [
        "Cringedows",
        "nejlepší Linux propaganda"
      ]
    },
    "2": {
      "matches": [
        "Windowsů"
      ],
      "replacements": [
        "Cringedowsů",
        "nejlepší Linux propagandy"
      ]
    },
    "3": {
      "matches": [
        "Windowsům"
      ],
      "replacements": [
        "Cringedowsům",
        "nejlepší Linux propagandě"
      ]
    },
    "4": {
      "matches": [
        "Windows"
      ],
      "replacements": [
        "Cringedows",
        "nejlepší Linux propagandu"
      ]
    },
    "5": {
      "matches": [
        "Windows"
      ],
      "replacements": [
        "Cringedows",
        "nejlepší Linux propagando"
      ]
    },
    "6": {
      "matches": [
        "Windowsech"
      ],
      "replacements": [
        "Cringedowsech",
        "nejlepší Linux propagandě"
      ]
    },
    "7": {
      "matches": [
        "Windowsy"
      ],
      "replacements": [
        "Cringedowsy",
        "nejlepší Linux propagandou"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/osobnosti/cz/vavra.json
{
  "name": "vavra",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Vávra",
        "Daniel Vávra"
      ],
      "replacements": [
        "CEO sebereflexe",
        "Gibon v Bentley",
        "Frý Spíč Mafia",
        "Ban Vávra"
      ]
    },
    "2": {
      "matches": [
        "Vávry",
        "Daniela Vávry"
      ],
      "replacements": [
        "CEO sebereflexe",
        "Gibona v Bentley",
        "Frý Spíč Mafie",
        "Bana Vávry"
      ]
    },
    "3": {
      "matches": [
        "Vávrovi",
        "Danielu Vávrovi"
      ],
      "replacements": [
        "CEO sebereflexe",
        "Gibonovi v Bentley",
        "Frý Spíč Mafii",
        "Banu Vávrovi"
      ]
    },
    "4": {
      "matches": [
        "Vávru",
        "Daniela Vávru"
      ],
      "replacements": [
        "CEO sebereflexe",
        "Gibona v Bentley",
        "Frý Spíč Mafii",
        "Bana Vávru"
      ]
    },
    "5": {
      "matches": [
        "Vávro",
        "Danieli Vávro"
      ],
      "replacements": [
        "CEO sebereflexe",
        "Gibone v Bentley",
        "Frý Spíč Mafie",
        "Bane Vávro"
      ]
    },
    "6": {
      "matches": [
        "Vávrovi",
        "Danielu Vávrovi"
      ],
      "replacements": [
        "CEO sebereflexe",
        "Gibonovi v Bentley",
        "Frý Spíč Mafii",
        "Banu Vávrovi"
      ]
    },
    "7": {
      "matches": [
        "Vávrou",
        "Danielem Vávrou"
      ],
      "replacements": [
        "CEO sebereflexe",
        "Gibonem v Bentley",
        "Frý Spíč Mafií",
        "Banem Vávrou"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/us/trump.json
{
  "name": "trump",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Trump",
        "Donald Trump"
      ],
      "replacements": [
        "Oranžgutan",
        "Oranžový tlučhuba",
        "Nejlepší ruský prezident",
        "Alzhajmrista",
        "Bombarduju, nebombarduju, bombarduju...",
        "Ředitel Zeměkoule",
        "Ochmatávač holčiček",
        "Ochmatávač Billa",
        "Donica Lewinsky",
        "No more wars",
        "Velký a krásný stratég",
        "Mírokurvce",
        "peDonald",
        "Agent Krasnov",
        "Cvičný terč"
      ]
    },
    "2": {
      "matches": [
        "Trumpa",
        "Donalda Trumpa"
      ],
      "replacements": [
        "Oranžgutana",
        "Oranžového tlučhuby",
        "Nejlepšího ruského prezidenta",
        "Alzhajmristy",
        "Bombarduju, nebombarduju, bombarduju...",
        "Ředitele Zeměkoule",
        "Ochmatávače holčiček",
        "Ochmatávače Billa",
        "Donicy Lewinsky",
        "No more wars",
        "Velkého a krásného stratéga",
        "Mírokurvce",
        "peDonalda",
        "Agenta Krasnova",
        "Cvičného terče"
      ]
    },
    "3": {
      "matches": [
        "Trumpovi",
        "Donaldu Trumpovi"
      ],
      "replacements": [
        "Oranžgutanovi",
        "Oranžovému tlučhubovi",
        "Nejlepšímu ruskému prezidentovi",
        "Alzhajmristovi",
        "Bombarduju, nebombarduju, bombarduju...",
        "Řediteli Zeměkoule",
        "Ochmatávači holčiček",
        "Ochmatávači Billa",
        "Donice Lewinsky",
        "No more wars",
        "Velkému a krásnému stratégovi",
        "Mírokurvcovi",
        "peDonaldovi",
        "Agentu Krasnovovi",
        "Cvičnému terči"
      ]
    },
    "4": {
      "matches": [
        "Trumpa",
        "Donalda Trumpa"
      ],
      "replacements": [
        "Oranžgutana",
        "Oranžového tlučhubu",
        "Nejlepšího ruského prezidenta",
        "Alzhajmristu",
        "Bombarduju, nebombarduju, bombarduju...",
        "Ředitele Zeměkoule",
        "Ochmatávače holčiček",
        "Ochmatávače Billa",
        "Donicu Lewinsky",
        "No more wars",
        "Velkého a krásného stratéga",
        "Mírokurvce",
        "peDonalda",
        "Agenta Krasnova",
        "Cvičný terč"
      ]
    },
    "5": {
      "matches": [
        "Trumpe",
        "Donalde Trumpe"
      ],
      "replacements": [
        "Oranžgutane",
        "Oranžový tlučhubo",
        "Nejlepší ruský prezidente",
        "Alzhajmristo",
        "Bombarduju, nebombarduju, bombarduju...",
        "Řediteli Zeměkoule",
        "Ochmatávači holčiček",
        "Ochmatávači Billa",
        "Donico Lewinsky",
        "No more wars",
        "Velký a krásný stratégu",
        "Mírokurvce",
        "peDonalde",
        "Agente Krasnove",
        "Cvičný terči"
      ]
    },
    "6": {
      "matches": [
        "Trumpovi",
        "Donaldu Trumpovi"
      ],
      "replacements": [
        "Oranžgutanovi",
        "Oranžovém tlučhubovi",
        "Nejlepším ruském prezidentovi",
        "Alzhajmristovi",
        "Bombarduju, nebombarduju, bombarduju...",
        "Řediteli Zeměkoule",
        "Ochmatávači holčiček",
        "Ochmatávači Billa",
        "Donice Lewinsky",
        "No more wars",
        "Velkém a krásném stratégovi",
        "Mírokurvcovi",
        "peDonaldovi",
        "Agentu Krasnovovi",
        "Cvičném terči"
      ]
    },
    "7": {
      "matches": [
        "Trumpem",
        "Donaldem Trumpem"
      ],
      "replacements": [
        "Oranžgutanem",
        "Oranžovým tlučhubou",
        "Nejlepším ruským prezidentem",
        "Alzhajmristou",
        "Bombarduju, nebombarduju, bombarduju...",
        "Ředitelem Zeměkoule",
        "Ochmatávačem holčiček",
        "Ochmatávačem Billa",
        "Donicou Lewinsky",
        "No more wars",
        "Velkým a krásným stratégem",
        "Mírokurvcem",
        "peDonaldem",
        "Agentem Krasnovem",
        "Cvičným terčem"
      ]
    }
  },
  "adjectives": {
    "to": {
      "matches": [
        "Trumpovo"
      ],
      "replacements": [
        "Alzhajmristovo",
        "Krasnovovo",
        "peDonaldovo",
        "Mírokurvcovo"
      ]
    },
    "ta": {
      "matches": [
        "Trumpova"
      ],
      "replacements": [
        "Alzhajmristova",
        "Krasnovova",
        "peDonaldova",
        "Mírokurvcova"
      ]
    },
    "ten": {
      "matches": [
        "Trumpův"
      ],
      "replacements": [
        "Alzhajmristův",
        "Krasnovův",
        "peDonaldův",
        "Mírokurvcův"
      ]
    },
    "ti": {
      "matches": [
        "Trumpovi"
      ],
      "replacements": [
        "Alzhajmristovi",
        "Krasnovovi",
        "peDonaldovi",
        "Mírokurvcovi"
      ]
    },
    "ty": {
      "matches": [
        "Trumpovy"
      ],
      "replacements": [
        "Alzhajmristovy",
        "Krasnovovy",
        "peDonaldovy",
        "Mírokurvcovy"
      ]
    },
    "te": {
      "matches": [
        "Trumpově"
      ],
      "replacements": [
        "Alzhajmristově",
        "Krasnovově",
        "peDonaldově",
        "Mírokurvcově"
      ]
    },
    "tu": {
      "matches": [
        "Trumpovu"
      ],
      "replacements": [
        "Alzhajmristovu",
        "Krasnovovu",
        "peDonaldovu",
        "Mírokurvcovu"
      ]
    },
    "tou": {
      "matches": [
        "Trumpovou"
      ],
      "replacements": [
        "Alzhajmristovou",
        "Krasnovovou",
        "peDonaldovou",
        "Mírokurvcovou"
      ]
    },
    "tim": {
      "matches": [
        "Trumpovým"
      ],
      "replacements": [
        "Alzhajmristovým",
        "Krasnovovým",
        "peDonaldovým",
        "Mírokurvcovým"
      ]
    },
    "tech": {
      "matches": [
        "Trumpových"
      ],
      "replacements": [
        "Alzhajmristových",
        "Krasnovových",
        "peDonaldových",
        "Mírokurvcových"
      ]
    },
    "temi": {
      "matches": [
        "Trumpovými"
      ],
      "replacements": [
        "Alzhajmristovými",
        "Krasnovovými",
        "peDonaldovými",
        "Mírokurvcovými"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/gross.json
{
  "name": "gross",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Stanislav Gross",
        "Gross"
      ],
      "replacements": [
        "Křišťálově čistý",
        "Ofina",
        "Myslím to upřímně"
      ]
    },
    "2": {
      "matches": [
        "Stanislava Grosse",
        "Grosse"
      ],
      "replacements": [
        "Křišťálově čistého",
        "Ofiny",
        "Myslím to upřímně"
      ]
    },
    "3": {
      "matches": [
        "Stanislavu Grossovi",
        "Grossovi"
      ],
      "replacements": [
        "Křišťálově čistému",
        "Ofinovi",
        "Myslím to upřímně"
      ]
    },
    "4": {
      "matches": [
        "Stanislava Grosse",
        "Grosse"
      ],
      "replacements": [
        "Křišťálově čistého",
        "Ofinu",
        "Myslím to upřímně"
      ]
    },
    "5": {
      "matches": [
        "Stanislave Grossi",
        "Grossi"
      ],
      "replacements": [
        "Křišťálově čistý",
        "Ofino",
        "Myslím to upřímně"
      ]
    },
    "6": {
      "matches": [
        "Stanislavu Grossovi",
        "Grossovi"
      ],
      "replacements": [
        "Křišťálově čistém",
        "Ofinovi",
        "Myslím to upřímně"
      ]
    },
    "7": {
      "matches": [
        "Stanislavem Grossem",
        "Grossem"
      ],
      "replacements": [
        "Křišťálově čistým",
        "Ofinou",
        "Myslím to upřímně"
      ]
    }
  },
  "adjectives": {
    "to": {
      "matches": [
        "Grossovo"
      ],
      "replacements": [
        "Křišťálovo",
        "Ofinovo"
      ]
    },
    "ta": {
      "matches": [
        "Grossova"
      ],
      "replacements": [
        "Křišťálova",
        "Ofinova"
      ]
    },
    "ten": {
      "matches": [
        "Grossův"
      ],
      "replacements": [
        "Křišťálův",
        "Ofinův"
      ]
    },
    "ti": {
      "matches": [
        "Grossovi"
      ],
      "replacements": [
        "Křišťálovi",
        "Ofinovi"
      ]
    },
    "ty": {
      "matches": [
        "Grossovy"
      ],
      "replacements": [
        "Křišťálovy",
        "Ofinovy"
      ]
    },
    "te": {
      "matches": [
        "Grossově"
      ],
      "replacements": [
        "Křišťálově",
        "Ofinově"
      ]
    },
    "tu": {
      "matches": [
        "Grossovu"
      ],
      "replacements": [
        "Křišťálovu",
        "Ofinovu"
      ]
    },
    "tou": {
      "matches": [
        "Grossovou"
      ],
      "replacements": [
        "Křišťálovou",
        "Ofinovou"
      ]
    },
    "tim": {
      "matches": [
        "Grossovým"
      ],
      "replacements": [
        "Křišťálovým",
        "Ofinovým"
      ]
    },
    "tech": {
      "matches": [
        "Grossových"
      ],
      "replacements": [
        "Křišťálových",
        "Ofinových"
      ]
    },
    "temi": {
      "matches": [
        "Grossovými"
      ],
      "replacements": [
        "Křišťálovými",
        "Ofinovými"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/osobnosti/cz/lipovska.json
{
  "name": "lipovska",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Hana Lipovská",
        "Lipovská"
      ],
      "replacements": [
        "Frý sPíč Absolutist",
        "Ošklivka Betty",
        "Strašidlo z České Televize",
        "Reklama na bouřku",
        "Wednesday Addamsová",
        "Frankensteinova nevěsta",
        "Požíračka duší",
        "La Muerte",
        "Carol Pifková"
      ]
    },
    "2": {
      "matches": [
        "Hany Lipovské",
        "Lipovské"
      ],
      "replacements": [
        "Frý sPíč Absolutistky",
        "Ošklivky Betty",
        "Strašidla z České Televize",
        "Reklamy na bouřku",
        "Wednesday Addamsové",
        "Frankensteinovy nevěsty",
        "Požíračky duší",
        "La Muerte",
        "Carol Pifkové"
      ]
    },
    "3": {
      "matches": [
        "Haně Lipovské",
        "Lipovské"
      ],
      "replacements": [
        "Frý sPíč Absolutistce",
        "Ošklivce Betty",
        "Strašidlu z České Televize",
        "Reklamě na bouřku",
        "Wednesday Addamsové",
        "Frankensteinově nevěstě",
        "Požíračce duší",
        "La Muerte",
        "Carol Pifkové"
      ]
    },
    "4": {
      "matches": [
        "Hanu Lipovskou",
        "Lipovskou"
      ],
      "replacements": [
        "Frý sPíč Absolutistku",
        "Ošklivku Betty",
        "Strašidlo z České Televize",
        "Reklamu na bouřku",
        "Wednesday Addamsovou",
        "Frankensteinovu nevěstu",
        "Požíračku duší",
        "La Muerte",
        "Carol Pifkovou"
      ]
    },
    "5": {
      "matches": [
        "Hano Lipovská",
        "Lipovská"
      ],
      "replacements": [
        "Frý sPíč Absolutistko",
        "Ošklivko Betty",
        "Strašidlo z České Televize",
        "Reklamo na bouřku",
        "Wednesday Addamsová",
        "Frankensteinova nevěsto",
        "Požíračko duší",
        "La Muerte",
        "Carol Pifková"
      ]
    },
    "6": {
      "matches": [
        "Haně Lipovské",
        "Lipovské"
      ],
      "replacements": [
        "Frý sPíč Absolutistce",
        "Ošklivce Betty",
        "Strašidlu z České Televize",
        "Reklamě na bouřku",
        "Wednesday Addamsové",
        "Frankensteinově nevěstě",
        "Požíračce duší",
        "La Muerte",
        "Carol Pifkové"
      ]
    },
    "7": {
      "matches": [
        "Hanou Lipovskou",
        "Lipovskou"
      ],
      "replacements": [
        "Frý sPíč Absolutistkou",
        "Ošklivkou Betty",
        "Strašidlem z České Televize",
        "Reklamou na bouřku",
        "Wednesday Addamsovou",
        "Frankensteinovou nevěstou",
        "Požíračkou duší",
        "La Muerte",
        "Carol Pifkovou"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/hrib.json
{
  "name": "hrib",
  "matchUpperCase": false,
  "matchLowerCase": false,
  "cases": {
    "1": {
      "matches": [
        "Hřib",
        "Zdeněk Hřib"
      ],
      "replacements": [
        "Mykologický zázrak",
        "Pražská zácpa",
        "Mám plán"
      ]
    },
    "2": {
      "matches": [
        "Hřiba",
        "Zdeňka Hřiba"
      ],
      "replacements": [
        "Mykologického zázraku",
        "Pražské zácpy",
        "Mám plánu"
      ]
    },
    "3": {
      "matches": [
        "Hřibovi",
        "Zdeňku Hřibovi"
      ],
      "replacements": [
        "Mykologickému zázraku",
        "Pražské zácpě",
        "Mám plánu"
      ]
    },
    "4": {
      "matches": [
        "Hřiba",
        "Zdeňka Hřiba"
      ],
      "replacements": [
        "Mykologický zázrak",
        "Pražskou zácpu",
        "Mám plán"
      ]
    },
    "5": {
      "matches": [
        "Hřibe",
        "Zdeňku Hřibe"
      ],
      "replacements": [
        "Mykologický zázraku",
        "Pražská zácpo",
        "Mám pláne"
      ]
    },
    "6": {
      "matches": [
        "Hřibovi",
        "Zdeňku Hřibovi"
      ],
      "replacements": [
        "Mykologickém zázraku",
        "Pražské zácpě",
        "Mám plánu"
      ]
    },
    "7": {
      "matches": [
        "Hřibem",
        "Zdeňkem Hřibem"
      ],
      "replacements": [
        "Mykologickým zázrakem",
        "Pražskou zácpou",
        "Mám plánem"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/other-sources/microslop/items/microsoft.json
{
  "name": "microsoft",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Microsoft"
      ],
      "replacements": [
        "Microslop",
        "Macroslop"
      ]
    },
    "2": {
      "matches": [
        "Microsoftu"
      ],
      "replacements": [
        "Microslopu",
        "Macroslopu"
      ]
    },
    "3": {
      "matches": [
        "Microsoftu"
      ],
      "replacements": [
        "Microslopu",
        "Macroslopu"
      ]
    },
    "4": {
      "matches": [
        "Microsoft"
      ],
      "replacements": [
        "Microslop",
        "Macroslop"
      ]
    },
    "5": {
      "matches": [
        "Microsofte"
      ],
      "replacements": [
        "Microslope",
        "Macroslope"
      ]
    },
    "6": {
      "matches": [
        "Microsoftu",
        "Microsoftě"
      ],
      "replacements": [
        "Microslopu",
        "Macroslopu",
        "Microslope",
        "Macroslope"
      ]
    },
    "7": {
      "matches": [
        "Microsoftem"
      ],
      "replacements": [
        "Microslopem",
        "Macroslopem"
      ]
    }
  }
}
